version: "3"
services:
  service-gateway:
    build:
      context: ./gateway
      dockerfile: ./docker-compose/Dockerfile.backendphp
    image: service-gateway
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    links:
      - postgresql-db-auth
      - nginx-service-informacoes-cadastrais
      - nginx-service-servicos-cliente
      - nginx-service-gestao-estrategia
      - nginx-service-dw-bi
    depends_on:
      - postgresql-db-auth
    networks:
      - gateway-network
      - informacoes-cadastrais-network
  service-gateway-migrations:
    image: service-gateway
    working_dir: /var/www/
    links:
      - postgresql-db-auth
    depends_on:
      - postgresql-db-auth
    command: ./docker-compose/configure.sh
    networks:
      - gateway-network
  nginx-service-gateway:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ./gateway
      dockerfile: ./docker-compose/Dockerfile.nginx
    image: nginx-service-gateway
    restart: unless-stopped
    ports:
      - "9091:80"
    depends_on:
      - service-gateway
    networks:
      - gateway-network
  service-informacoes-cadastrais:
    build:
      context: ./modulo-informacoes-cadastrais
      dockerfile: ./docker-compose/Dockerfile.backendphp
    image: service-informacoes-cadastrais
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    links:
      - postgresql-db-shippingcompany
    networks:
      - informacoes-cadastrais-network
  service-informacoes-cadastrais-migrations:
    image: service-informacoes-cadastrais
    working_dir: /var/www/
    links:
      - postgresql-db-shippingcompany
    depends_on:
      - postgresql-db-shippingcompany
    command: ./docker-compose/configure.sh
    networks:
      - informacoes-cadastrais-network
  nginx-service-informacoes-cadastrais:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ./modulo-informacoes-cadastrais
      dockerfile: ./docker-compose/Dockerfile.nginx
    image: nginx-service-informacoes-cadastrais
    restart: unless-stopped
    #ports:
    #  - "9092:80"
    depends_on:
      - service-informacoes-cadastrais
    networks:
      - informacoes-cadastrais-network
  service-servicos-cliente:
    build:
      context: ./modulo-servicos-cliente
      dockerfile: ./docker-compose/Dockerfile.backendphp
    image: service-servicos-cliente
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - gateway-network
  nginx-service-servicos-cliente:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ./modulo-servicos-cliente
      dockerfile: ./docker-compose/Dockerfile.nginx
    image: nginx-service-servicos-cliente
    restart: unless-stopped
    #ports:
    #  - "9093:80"
    depends_on:
      - service-servicos-cliente
    networks:
      - gateway-network
  service-gestao-estrategia:
    build:
      context: ./modulo-gestao-estrategia
      dockerfile: ./docker-compose/Dockerfile.backendphp
    image: service-gestao-estrategia
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - gateway-network
  nginx-service-gestao-estrategia:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ./modulo-gestao-estrategia
      dockerfile: ./docker-compose/Dockerfile.nginx
    image: nginx-service-gestao-estrategia
    restart: unless-stopped
    #ports:
    #  - "9094:80"
    depends_on:
      - service-gestao-estrategia
    networks:
      - gateway-network
  service-dw-bi:
    build:
      context: ./modulo-dw-bi
      dockerfile: ./docker-compose/Dockerfile.backendphp
    image: service-dw-bi
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - gateway-network
  nginx-service-dw-bi:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ./modulo-dw-bi
      dockerfile: ./docker-compose/Dockerfile.nginx
    image: nginx-service-dw-bi
    restart: unless-stopped
    #ports:
    #  - "9095:80"
    depends_on:
      - service-dw-bi
    networks:
      - gateway-network
  postgresql-db-auth:
    image: postgres
    restart: always
    env_file:
      - ./gateway/docker-compose/postgres/database.env
    ports:
      - "15432:5432"
    volumes:
      - ./gateway/datadbs/postgres:/var/lib/postgresql/data
      - ./gateway/docker-compose/postgres/dumps/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    networks:
      - gateway-network
    container_name: postgresql-db-auth
  postgresql-db-shippingcompany:
    image: postgres
    restart: always
    env_file:
      - ./modulo-informacoes-cadastrais/docker-compose/postgres/database.env
    ports:
      - "25432:5432"
    volumes:
      - ./modulo-informacoes-cadastrais/datadbs/postgres:/var/lib/postgresql/data
      - ./modulo-informacoes-cadastrais/docker-compose/postgres/dumps/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    networks:
      - informacoes-cadastrais-network
    container_name: postgresql-db-shippingcompany
networks:
  gateway-network:
    driver: bridge
  informacoes-cadastrais-network:
    driver: bridge