version: "3"
services:
  service-gateway:
    build:
      context: ../gateway
      dockerfile: ../gateway/docker-compose/Dockerfile.backendphp
    image: service-gateway
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 64M
    volumes:
      - ../gateway:/var/www
    links:
      - postgresql-db-auth
      - nginx-service-servicos-cliente
      - nginx-service-gestao-estrategia
    depends_on:
      - postgresql-db-auth
    networks:
      - teste
  service-gateway-migrations:
    image: service-gateway
    working_dir: /var/www/
    volumes:
      - ../gateway:/var/www
    links:
      - postgresql-db-auth
    depends_on:
      - postgresql-db-auth
    command: ./docker-compose/configure.sh
    networks:
      - teste
  nginx-service-gateway:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ../gateway
      dockerfile: ../gateway/docker-compose/Dockerfile.nginx
    image: nginx-service-gateway
    restart: unless-stopped
    ports:
      - "9091:80"
    volumes:
      - ../gateway:/var/www
    depends_on:
      - service-gateway
    networks:
      - teste
  service-informacoes-cadastrais:
    build:
      context: ../modulo-informacoes-cadastrais
      dockerfile: ../modulo-informacoes-cadastrais/docker-compose/Dockerfile.backendphp
    image: service-informacoes-cadastrais
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M
    volumes:
      - ../modulo-informacoes-cadastrais:/var/www
    networks:
      - teste
  nginx-service-informacoes-cadastrais:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ../modulo-informacoes-cadastrais
      dockerfile: ../modulo-informacoes-cadastrais/docker-compose/Dockerfile.nginx
    image: nginx-service-informacoes-cadastrais
    restart: unless-stopped
    ports:
      - "9092:80"
    volumes:
      - ../modulo-informacoes-cadastrais:/var/www
    depends_on:
      - service-informacoes-cadastrais
    networks:
      - teste
  service-servicos-cliente:
    build:
      context: ../modulo-servicos-cliente
      dockerfile: ../modulo-servicos-cliente/docker-compose/Dockerfile.backendphp
    image: service-servicos-cliente
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M
    volumes:
      - ../modulo-servicos-cliente:/var/www
    networks:
      - teste
  nginx-service-servicos-cliente:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ../modulo-servicos-cliente
      dockerfile: ../modulo-servicos-cliente/docker-compose/Dockerfile.nginx
    image: nginx-service-servicos-cliente
    restart: unless-stopped
    ports:
      - "9093:80"
    volumes:
      - ../modulo-servicos-cliente:/var/www
    depends_on:
      - service-servicos-cliente
    networks:
      - teste
  service-gestao-estrategia:
    build:
      context: ../modulo-gestao-estrategia
      dockerfile: ../modulo-gestao-estrategia/docker-compose/Dockerfile.backendphp
    image: service-gestao-estrategia
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M
    volumes:
      - ../modulo-gestao-estrategia:/var/www
    networks:
      - teste
  nginx-service-gestao-estrategia:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ../modulo-gestao-estrategia
      dockerfile: ../modulo-gestao-estrategia/docker-compose/Dockerfile.nginx
    image: nginx-service-gestao-estrategia
    restart: unless-stopped
    ports:
      - "9094:80"
    volumes:
      - ../modulo-gestao-estrategia:/var/www
    depends_on:
      - service-gestao-estrategia
    networks:
      - teste
  service-dw-bi:
    build:
      context: ../modulo-dw-bi
      dockerfile: ../modulo-dw-bi/docker-compose/Dockerfile.backendphp
    image: service-dw-bi
    restart: unless-stopped
    working_dir: /var/www/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M
    volumes:
      - ../modulo-dw-bi:/var/www
    networks:
      - teste
  nginx-service-dw-bi:
    build:
      args:
        server_conf: ./docker-compose/nginx/local.conf
      context: ../modulo-dw-bi
      dockerfile: ../modulo-dw-bi/docker-compose/Dockerfile.nginx
    image: nginx-service-dw-bi
    restart: unless-stopped
    ports:
      - "9095:80"
    volumes:
      - ../modulo-dw-bi:/var/www
    depends_on:
      - service-dw-bi
    networks:
      - teste
  postgresql-db-auth:
    image: postgres
    restart: always
    env_file:
      - ../gateway/docker-compose/postgres/database.env
    ports:
      - "15432:5432"
    volumes:
      - ../gateway/datadbs/postgres:/var/lib/postgresql/data
      - ../gateway/docker-compose/postgres/dumps/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    networks:
      - teste
    container_name: postgresql-db-auth
networks:
  teste:
    driver: bridge
