FROM nginx
USER root
ARG server_conf
WORKDIR /var/www
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    gnupg2 \
    openssl \
    nano \
    libpq-dev
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www
COPY ./ /var/www
#COPY ./docker-compose/nginx/certs /etc/nginx/conf.d/certs
COPY ${server_conf} /etc/nginx/conf.d/default.conf
RUN chown -R www-data:www-data /var/www \
    && chmod -R 775 /var/www/ \
    && chmod -R 777 /var/www/storage
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
