FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
USER root

# Set working directory
WORKDIR /var/www

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y apt-utils

# Install system dependencies
RUN apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    gnupg2 \
    openssl \
    unzip \
    nano  \
    libicu-dev \
    libxslt-dev \
    libpq-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libgd-dev \
    libgmp-dev \
    libbz2-dev \
    zlib1g-dev \
    libzip-dev \
    libssl-dev \
    libssh2-1-dev \
    libmemcached-dev \
    libmemcached11 

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install various PHP extensions
RUN docker-php-ext-install \
    session \
    json \
    curl \
    fileinfo \
    gmp \
    ftp \
    soap \
    sockets \
    calendar \
    sysvmsg \
    sysvsem \
    sysvshm

RUN docker-php-ext-install \
    bcmath \
    intl \
    mbstring \
    mysqli \
    pcntl \
    pdo_mysql \
    pdo_pgsql \
    zip \
    dom \
    xmlrpc \
    xsl \
    exif \
    gd \
    opcache

RUN docker-php-ext-configure bcmath --enable-bcmath \
    && docker-php-ext-configure pcntl --enable-pcntl \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql \
    && docker-php-ext-configure mbstring --enable-mbstring \
    && docker-php-ext-configure soap --enable-soap

RUN docker-php-ext-configure gd \
    && docker-php-ext-enable opcache

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /var/www

# Get latest Composer

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY ./docker-compose/php/local.ini /usr/local/etc/php/php.ini
COPY ./docker-compose/php/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./ /var/www
RUN composer install \
    && composer update

RUN chown -R www-data:www-data /var/www \
    && chmod -R 775 /var/www/ \
    && chmod -R 777 /var/www/storage

# Expose port 9000 and start php-fpm server

CMD ["php-fpm"]

EXPOSE 9000